spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/examination_system?characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
  thymeleaf:
#  采用非严格HTML5
    mode: LEGACYHTML5
    encoding: utf-8
    content-type: text/html
    #   开发时关闭缓存，不然没法看到实时页面
    cache: false
#server:
#  port: 8081
#  context-path: /boot

